bring up to date
NeonGeckoCom/neon_solvers pull request #6
Opened 2023-02-04 23:27 UTC by JarbasAl

for integration with https://github.com/OpenVoiceOS/ovos-backend-client/pull/28

2023-02-15 18:34 UTC, NeonDaniel requested changes

2023-02-15 18:34 UTC, NeonDaniel commented on neon_solvers/__init__.py
> +                continue
Can this include a debug log that the plugin is disabled

2023-02-15 18:37 UTC, NeonDaniel commented on neon_solvers/__init__.py
> +            config = self.config.get(plug) or {}
should be `plug_name`, not `plug`?

2023-02-15 18:38 UTC, NeonDaniel commented on neon_solvers/__init__.py
> +                config = self.config.get(plug) or {}
`config` already defined?

2023-04-13 20:48 UTC, JarbasAl commented
replaced by https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/140

2023-04-13 21:04 UTC, JarbasAl commented
nvm, the service should stay here, only base class moved, will update PR

2023-09-24 20:37 UTC, closed without merging